name: Build and Push

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.11.1

    - name: Login to GHCR
      uses: docker/login-action@v3.5.0
      with:
        registry: ghcr.io/baffinbay
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set envs
      run: |
        echo "GITHUB_REPO=$(echo ${GITHUB_REPOSITORY})" >> $GITHUB_ENV
        echo "GITHUB_BRANCH_NAME=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | sed 's/[^a-z0-9_\.-]/-/g')" >> $GITHUB_ENV
        echo "GITHUB_INCREMENTAL_ID=$(git rev-list --count HEAD)" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ env.GITHUB_REPO }}:${{ env.GITHUB_BRANCH_NAME }}-${{ env.GITHUB_INCREMENTAL_ID }}
